// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: fUD5Y2ykPycj9iawsCxvT2

import * as React from "react";
import { hasVariant, ensureGlobalVariants } from "@plasmicapp/react-web";
import { StrapiCredentialsProvider } from "@plasmicpkgs/plasmic-strapi";

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  strapiCredentialsProviderProps?: Partial<
    Omit<React.ComponentProps<typeof StrapiCredentialsProvider>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, strapiCredentialsProviderProps } = props;

  return (
    <StrapiCredentialsProvider
      {...strapiCredentialsProviderProps}
      host={
        strapiCredentialsProviderProps &&
        "host" in strapiCredentialsProviderProps
          ? strapiCredentialsProviderProps.host!
          : "https://democms.throughwave.co.th"
      }
      token={
        strapiCredentialsProviderProps &&
        "token" in strapiCredentialsProviderProps
          ? strapiCredentialsProviderProps.token!
          : "ba779d611824e854a30a70f9f8a4e59bf97c1b9517a68620e2331b41e034e82fc012bd51fa2d207e1cdb2281aa2e01d1545553dca1b62379b433ba70e4410ff4d6adafe34db0e8b73867b1097d6164c2973391924ae10410c965d4932694c5c549c5764abe7a673ffd366970780aefcc84c817aebd61465a412ac1a6bc052c4c"
      }
    >
      {children}
    </StrapiCredentialsProvider>
  );
}
