// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: pnayxrZQDQNLaMhqWY9Kua

import * as React from "react";
import { hasVariant, ensureGlobalVariants } from "@plasmicapp/react-web";
import { StrapiCredentialsProvider } from "@plasmicpkgs/plasmic-strapi";

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  strapiCredentialsProviderProps?: Partial<
    Omit<React.ComponentProps<typeof StrapiCredentialsProvider>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, strapiCredentialsProviderProps } = props;

  return (
    <StrapiCredentialsProvider
      {...strapiCredentialsProviderProps}
      host={
        strapiCredentialsProviderProps &&
        "host" in strapiCredentialsProviderProps
          ? strapiCredentialsProviderProps.host!
          : "https://strapi-app.plasmic.app"
      }
      token={
        strapiCredentialsProviderProps &&
        "token" in strapiCredentialsProviderProps
          ? strapiCredentialsProviderProps.token!
          : undefined
      }
    >
      {children}
    </StrapiCredentialsProvider>
  );
}
